export const exceptions = {
  resourceNotFound: '{resource} com ID {id} não encontrado.',
  dataIntegrityViolation: 'Não é possível excluir, pois está sendo utilizado.',
  validation: 'Erro de validação',
  unauthorized: 'Usuário não autorizado',
  forbidden: 'Acesso negado',
  internalError: 'Erro interno do servidor',
};
